let mevcutEnlem=39.93,mevcutBoylam=32.85,mevcutZamanDilimi="Europe/Istanbul",havaVerisi=null;
const $=id=>document.getElementById(id),ayarlar=JSON.parse(localStorage.getItem("havaDurumuAyarlar")||"{}");
$("sicaklikBirimi").value=ayarlar.sicaklikBirimi||"celsius";$("ruzgarBirimi").value=ayarlar.ruzgarBirimi||"kmh";
function saatiGuncelle(){const d=new Date();try{$("saat").textContent=new Intl.DateTimeFormat("tr-TR",{timeZone:mevcutZamanDilimi,hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(d);$("tarih").textContent=new Intl.DateTimeFormat("tr-TR",{timeZone:mevcutZamanDilimi,year:"numeric",month:"long",day:"numeric",weekday:"long"}).format(d)}catch{$("saat").textContent=d.toLocaleTimeString("tr-TR")}}setInterval(saatiGuncelle,1000);saatiGuncelle();
function bildirim(m,h=false){const e=$("bildirim");e.textContent=m;e.className=`bildirim goster${h?" hata":""}`}function kapat(){$("bildirim").className="bildirim"}
function sonlar(){return JSON.parse(localStorage.getItem("sonArananSehirler")||"[]")}function sonlariCiz(){const e=$("sonAramalar"),l=sonlar();e.innerHTML=l.map((s,i)=>`<button class="sehir-etiketi" type="button" data-i="${i}">${s.name}</button>`).join("");e.querySelectorAll("button").forEach(b=>b.onclick=()=>sehirSec(sonlar()[b.dataset.i]))}function sonKaydet(s){const l=sonlar().filter(x=>x.name!==s.name||x.country!==s.country);l.unshift({name:s.name,country:s.country,admin1:s.admin1,latitude:s.latitude,longitude:s.longitude});localStorage.setItem("sonArananSehirler",JSON.stringify(l.slice(0,5)));sonlariCiz()}
$("bgFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=x=>document.body.style.backgroundImage=`url("${x.target.result}")`;r.readAsDataURL(f)};$("aramaButonu").onclick=sehirAra;$("sehirInput").onkeydown=e=>{if(e.key==="Enter")sehirAra()};[$("sicaklikBirimi"),$("ruzgarBirimi")].forEach(e=>e.onchange=()=>{localStorage.setItem("havaDurumuAyarlar",JSON.stringify({sicaklikBirimi:$("sicaklikBirimi").value,ruzgarBirimi:$("ruzgarBirimi").value}));if(havaVerisi)goster(havaVerisi)});
async function sehirAra(){const ad=$("sehirInput").value.trim();if(!ad)return;bildirim("Şehirler aranıyor…");try{const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(ad)}&count=8&language=tr&format=json`);if(!r.ok)throw 0;const d=await r.json();if(!d.results?.length){bildirim("Bu isimle bir şehir bulunamadı.",true);return}sonuclariGoster(d.results);kapat()}catch{bildirim("Şehir aranırken bağlantı hatası oluştu.",true)}}
function sonuclariGoster(l){const e=$("sehirSonuclari");e.innerHTML=l.map((s,i)=>`<button class="sonuc" type="button" data-i="${i}"><b>${s.name}</b><small>${[s.admin1,s.country].filter(Boolean).join(", ")}</small></button>`).join("");e.classList.add("goster");e.querySelectorAll("button").forEach(b=>b.onclick=()=>sehirSec(l[b.dataset.i]))}function sehirSec(s){mevcutEnlem=s.latitude;mevcutBoylam=s.longitude;$("sehir").textContent=s.name;$("sehirInput").value="";$("sehirSonuclari").classList.remove("goster");sonKaydet(s);havaDurumuGetir();sembolikResimGetir(s.name)}
function sembolikResimGetir(ad){fetch(`https://tr.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(ad)}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>d.originalimage?.source||Promise.reject()).then(u=>document.body.style.backgroundImage=`url("${u}")`).catch(()=>document.body.style.backgroundImage="linear-gradient(135deg,#0f172a,#0c4a6e)")}
async function havaDurumuGetir(){bildirim("Hava durumu güncelleniyor…");try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${mevcutEnlem}&longitude=${mevcutBoylam}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&daily=sunrise,sunset,uv_index_max,precipitation_probability_max&timezone=auto`;const r=await fetch(u);if(!r.ok)throw 0;havaVerisi=await r.json();mevcutZamanDilimi=havaVerisi.timezone||mevcutZamanDilimi;saatiGuncelle();goster(havaVerisi);kapat()}catch{bildirim("Hava bilgisi alınamadı. Bağlantını kontrol edip tekrar dene.",true)}}
function goster(d){const a=d.current,g=d.daily,f=$("sicaklikBirimi").value==="fahrenheit",m=$("ruzgarBirimi").value==="mph",s=x=>f?`${Math.round(x*9/5+32)}°F`:`${Math.round(x)}°C`;$("sicaklik").textContent=s(a.temperature_2m);$("hissedilen").textContent=s(a.apparent_temperature);$("nem").textContent=`%${a.relative_humidity_2m}`;$("ruzgar").textContent=m?`${Math.round(a.wind_speed_10m*.621371)} mph`:`${Math.round(a.wind_speed_10m)} km/s`;$("uv").textContent=g.uv_index_max[0]??"--";$("gundogumu").textContent=g.sunrise[0]?.split("T")[1]||"--:--";$("gunbatimi").textContent=g.sunset[0]?.split("T")[1]||"--:--";$("durum").textContent=metin(a.weather_code);$("havaIkonu").textContent=ikon(a.weather_code);uyarilar(a,g)}
function uyarilar(a,g){const l=[];if((g.uv_index_max[0]||0)>=6)l.push("☀️ UV indeksi yüksek: güneşten korunmayı unutma.");if([95,96,99].includes(a.weather_code))l.push("⛈️ Fırtına uyarısı: mümkünse kapalı alanda kal.");if(a.temperature_2m<=0)l.push("❄️ Don riski: buzlanmaya karşı dikkatli ol.");if((g.precipitation_probability_max[0]||0)>=60)l.push(`☔ Yağış olasılığı yüksek: %${g.precipitation_probability_max[0]}.`);$("uyarilar").innerHTML=l.map(x=>`<div class="uyari">${x}</div>`).join("")}
function ikon(c){if(c===0)return"☀️";if([1,2].includes(c))return"🌤️";if(c===3)return"☁️";if([45,48].includes(c))return"🌫️";if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(c))return"🌧️";if([71,73,75,77,85,86].includes(c))return"❄️";if([95,96,99].includes(c))return"⛈️";return"🌡️"}function metin(c){return({0:"Açık / Güneşli",1:"Çoğunlukla Açık",2:"Parçalı Bulutlu",3:"Kapalı / Bulutlu",45:"Sisli",48:"Kırağılı Sis",51:"Hafif Çiseleme",53:"Çiseleme",55:"Yoğun Çiseleme",61:"Hafif Yağmurlu",63:"Yağmurlu",65:"Şiddetli Yağmurlu",71:"Hafif Karlı",73:"Karlı",75:"Yoğun Karlı",95:"Gökgürültülü Fırtına"})[c]||"Hava Durumu Bilinmiyor"}
sonlariCiz();havaDurumuGetir();sembolikResimGetir("Ankara");setInterval(havaDurumuGetir,600000);
